const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const pct=(x,d=1)=>x==null||Number.isNaN(+x)?'—':`${(+x*100).toFixed(d)}%`;const num=(x,d=2)=>x==null||Number.isNaN(+x)?'—':(+x).toFixed(d);
const metric=(label,value)=>`<div class="metric"><div class="label">${label}</div><div class="value">${value}</div></div>`;
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active-panel'));b.classList.add('active');$('#'+b.dataset.target).classList.add('active-panel');window.dispatchEvent(new Event('resize'));}));
function plot(id,data,layout={}){Plotly.newPlot(id,data,{paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dbe7f5'},margin:{l:48,r:20,t:20,b:55},...layout},{responsive:true,displayModeBar:false});}
function renderMetrics(m){$('#metrics').innerHTML=[['Ann. return',pct(m.annualized_return)],['Ann. volatility',pct(m.annualized_volatility)],['Sharpe',num(m.sharpe)],['Tracking error',pct(m.tracking_error)],['Info ratio',num(m.information_ratio)],['Max drawdown',pct(m.max_drawdown)],['Beta',num(m.beta)],['Sortino',num(m.sortino)],['Active return',pct(m.active_annualized_return)],['Daily ES 95%',pct(m.daily_expected_shortfall_95,2)]].map(x=>metric(...x)).join('');}
function renderHoldings(h){const names=h.map(x=>x.company),weights=h.map(x=>+x.weight||0),risk=h.map(x=>+x.risk_contribution||0);plot('weightsChart',[{type:'pie',labels:names,values:weights,hole:.45,textinfo:'label+percent'}],{showlegend:false});plot('riskChart',[{type:'bar',name:'Weight',x:names,y:weights},{type:'bar',name:'Risk contribution',x:names,y:risk}],{barmode:'group',yaxis:{tickformat:'.0%'}});const sec={};h.forEach(x=>{if(x.sector)sec[x.sector]=(sec[x.sector]||0)+(+x.weight||0)});plot('sectorChart',[{type:'bar',x:Object.keys(sec),y:Object.values(sec)}],{yaxis:{tickformat:'.0%'}});$('#holdingsTable').innerHTML=`<thead><tr><th>Company</th><th>Sector</th><th>Weight</th><th>Risk contribution</th></tr></thead><tbody>${h.map(x=>`<tr><td>${x.company||'—'}</td><td>${x.sector||'—'}</td><td>${pct(x.weight)}</td><td>${pct(x.risk_contribution)}</td></tr>`).join('')}</tbody>`;}
function renderGrowth(ts){if(!ts?.length)return;plot('growthChart',[{type:'scatter',mode:'lines',name:'Portfolio',x:ts.map(x=>x.date),y:ts.map(x=>x.portfolio_growth)},{type:'scatter',mode:'lines',name:'Benchmark',x:ts.map(x=>x.date),y:ts.map(x=>x.benchmark_growth)}]);}
function renderRisk(d){if(d.factors?.length)plot('factorChart',[{type:'bar',x:d.factors.map(x=>x.factor),y:d.factors.map(x=>x.exposure)}]);if(d.stress?.length)plot('stressChart',[{type:'bar',x:d.stress.map(x=>x.scenario),y:d.stress.map(x=>x.estimated_return)}],{yaxis:{tickformat:'.0%'}});}
function renderPhilosophy(p){if(!p||!Object.keys(p).length){$('#philosophyCard').innerHTML='<h2>Portfolio philosophy</h2><p class="muted">No public philosophy text has been published yet.</p>';return;}const fields=[['Investment Philosophy','investment_philosophy'],['Portfolio Objective','portfolio_objective'],['Research Process','research_process'],['Selection Criteria','selection_criteria'],['Position Sizing','position_sizing'],['Risk Management','risk_management'],['Sell Discipline','sell_discipline'],['Monitoring & Review','monitoring_and_review']];$('#philosophyCard').innerHTML=`<h2>Portfolio Philosophy</h2><div class="metric-grid compact">${metric('Benchmark',p.benchmark||'—')}${metric('Time horizon',p.time_horizon||'—')}${metric('Return objective',p.return_objective||'—')}</div><div class="thesis-grid">${fields.filter(x=>p[x[1]]).map(([t,k])=>`<div class="thesis-block"><h3>${t}</h3><p>${p[k]}</p></div>`).join('')}</div>`;}
function renderThesisList(items){const sel=$('#companySelect');sel.innerHTML=items.map((x,i)=>`<option value="${i}">${x.company}</option>`).join('');const show=()=>{const x=items[+sel.value||0];$('#thesisSummary').innerHTML=[['Weight',pct(x.weight)],['Conviction',x.conviction==null?'—':`${num(x.conviction,1)} / 5`],['Research score',x.composite_score==null?'—':`${num(x.composite_score,2)} / 5`],['Expected return',pct(x.expected_annual_return)],['Time horizon',x.time_horizon||'—']].map(v=>metric(...v)).join('');const scores=x.scores||{};plot('scoreChart',[{type:'bar',x:Object.keys(scores).map(k=>k.replaceAll('_',' ')),y:Object.values(scores)}],{yaxis:{range:[0,5]}});const fields=[['Investment Thesis','investment_thesis'],['Why I Own It','why_owned'],['Competitive Advantage / Moat','competitive_advantage'],['Growth Drivers','growth_drivers'],['Valuation Rationale','valuation_rationale'],['Catalysts','catalysts'],['Key Risks','key_risks'],['Falsification / Sell Condition','sell_condition'],['Monitoring KPI','monitoring_kpi'],['Public Notes','public_notes']];$('#thesisBody').innerHTML=fields.filter(f=>x[f[1]]).map(([t,k])=>`<div class="thesis-block"><h3>${t}</h3><p>${x[k]}</p></div>`).join('')||'<p class="muted">No public thesis text has been published for this company yet.</p>';};sel.onchange=show;show();}
async function init(){try{const r=await fetch(`data/portfolio_snapshot.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('snapshot unavailable');const d=await r.json();$('#freshness').textContent=`Latest validated portfolio snapshot: ${d.generated_utc||'available'}`;renderMetrics(d.metrics||{});renderHoldings(d.holdings||[]);renderGrowth(d.timeseries||[]);renderRisk(d);renderPhilosophy(d.portfolio_philosophy||{});renderThesisList(d.theses||[]);}catch(e){$('#freshness').textContent='Latest portfolio snapshot is temporarily unavailable.';$('#portfolio').insertAdjacentHTML('afterbegin','<article class="card"><h2>Data temporarily unavailable</h2><p>Please reload after the next successful portfolio refresh.</p></article>');}}
init();