const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const pct=(x,d=1)=>x==null||Number.isNaN(+x)?'—':`${(+x*100).toFixed(d)}%`;
const num=(x,d=2)=>x==null||Number.isNaN(+x)?'—':(+x).toFixed(d);
const mult=(x,d=1)=>x==null||Number.isNaN(+x)?'—':`${(+x).toFixed(d)}x`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const metric=(label,value,sub='')=>`<div class="metric"><div class="label">${esc(label)}</div><div class="value">${esc(value)}</div>${sub?`<div class="metric-sub">${esc(sub)}</div>`:''}</div>`;
const fieldCard=(title,value,kind='')=>value?`<article class="card thesis-block thesis-section ${kind}"><h2>${esc(title)}</h2><p>${esc(value)}</p></article>`:'';
let thesisItems=[];let researchItems=[];let appData=null;let benchmarkRef=null;

function activateTab(target){
  $$('.tab[data-target]').forEach(x=>x.classList.toggle('active',x.dataset.target===target));
  $$('.panel').forEach(x=>x.classList.toggle('active-panel',x.id===target));
  history.replaceState(null,'',`#${target}`);
  setTimeout(()=>$$(`#${target} .js-plotly-plot`).forEach(el=>Plotly.Plots.resize(el)),30);
  window.scrollTo({top:document.querySelector('.tabs').offsetTop,behavior:'smooth'});
}
$$('.tab[data-target]').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.target)));
$$('[data-open-tab]').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.openTab)));
function plot(id,data,layout={}){const el=$(`#${id}`);if(!el)return;Plotly.newPlot(id,data,{paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#dbe7f5'},margin:{l:48,r:20,t:20,b:55},...layout},{responsive:true,displayModeBar:false});}
function noData(id,text='Available after the next successful research refresh.'){const el=$(`#${id}`);if(el)el.innerHTML=`<div class="empty-state">${esc(text)}</div>`;}

function applyOverrides(snapshot,overrides){
  const map=new Map((overrides?.companies||[]).map(x=>[x.match_company,x]));
  const merge=x=>{const o=map.get(x.company);return o?{...x,company:o.display_company||x.company,expected_annual_return:x.expected_annual_return??o.expected_annual_return,country:x.country??o.country,currency:x.currency??o.currency}:x};
  ['holdings','theses','attribution','reverse_dcf'].forEach(k=>snapshot[k]=(snapshot[k]||[]).map(merge));
  return snapshot;
}
function canonicalSector(s){return ({'Technology':'Information Technology','Financial Services':'Financials','Consumer Cyclical':'Consumer Discretionary','Healthcare':'Health Care','Consumer Defensive':'Consumer Staples','Basic Materials':'Materials'})[s]||s||'Unknown';}
function weightedExpected(holdings){const e=holdings.filter(x=>x.expected_annual_return!=null&&x.weight!=null);const w=e.reduce((s,x)=>s+(+x.weight||0),0);return w?e.reduce((s,x)=>s+(+x.weight||0)*(+x.expected_annual_return||0),0)/w:null;}
function dateOf(s){const d=new Date(`${s}T00:00:00Z`);return Number.isNaN(d.getTime())?null:d;}
function isoDate(d){return d.toISOString().slice(0,10);}
function sortedSeries(ts){return (ts||[]).filter(x=>dateOf(x.date)).sort((a,b)=>xDate(a)-xDate(b));}
function xDate(x){return dateOf(x.date)?.getTime()||0;}
function seriesReturn(ts,field,startDate,annualize=false){const rows=(ts||[]).filter(x=>dateOf(x.date)&&x[field]!=null&&(!startDate||dateOf(x.date)>=startDate));if(rows.length<2)return null;const first=+rows[0][field],last=+rows[rows.length-1][field];if(!(first>0&&last>0))return null;const total=last/first-1;if(!annualize)return total;const years=(dateOf(rows[rows.length-1].date)-dateOf(rows[0].date))/(365.25*86400000);return years>0.5?Math.pow(last/first,1/years)-1:total;}
function startOfQuarter(d){return new Date(Date.UTC(d.getUTCFullYear(),Math.floor(d.getUTCMonth()/3)*3,1));}
function periodRows(ts){if(!ts?.length)return[];const end=dateOf(ts[ts.length-1].date);const starts={MTD:new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),1)),QTD:startOfQuarter(end),YTD:new Date(Date.UTC(end.getUTCFullYear(),0,1)),"1Y":new Date(Date.UTC(end.getUTCFullYear()-1,end.getUTCMonth(),end.getUTCDate())),"3Y":new Date(Date.UTC(end.getUTCFullYear()-3,end.getUTCMonth(),end.getUTCDate())),"5Y":new Date(Date.UTC(end.getUTCFullYear()-5,end.getUTCMonth(),end.getUTCDate()))};return ['MTD','QTD','YTD','1Y','3Y','5Y','Since analysis start'].map(label=>{const annual=label==='3Y'||label==='5Y'||label==='Since analysis start';const start=label==='Since analysis start'?null:starts[label];const p=seriesReturn(ts,'portfolio_growth',start,annual);const b=seriesReturn(ts,'benchmark_growth',start,annual);return{label,portfolio:p,benchmark:b,active:p!=null&&b!=null?p-b:null,annualized:annual};});}
function drawdowns(ts,field){let peak=-Infinity;return(ts||[]).map(x=>{const v=+x[field];if(!Number.isFinite(v))return null;peak=Math.max(peak,v);return peak>0?v/peak-1:null;});}
function calendarReturns(ts){const groups={};(ts||[]).forEach(x=>{const d=dateOf(x.date);if(!d)return;const y=d.getUTCFullYear();(groups[y]??=[]).push(x)});return Object.keys(groups).sort((a,b)=>b-a).map(y=>{const r=groups[y];return{year:y,portfolio:seriesReturn(r,'portfolio_growth'),benchmark:seriesReturn(r,'benchmark_growth')}}).filter(x=>x.portfolio!=null).slice(0,8);}
function monthlyReturns(ts){const groups={};(ts||[]).forEach(x=>{const d=dateOf(x.date);if(!d)return;const key=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;(groups[key]??=[]).push(x)});const vals={};Object.entries(groups).forEach(([k,r])=>vals[k]=seriesReturn(r,'portfolio_growth'));return vals;}

function renderHero(d,bref){const ts=d.timeseries||[];const md=d.metadata||{};const start=md.analysis_start||ts[0]?.date||'—';const benchmark=md.benchmark||d.portfolio_philosophy?.benchmark||bref?.benchmark||'S&P 500';$('#heroFacts').innerHTML=[['Benchmark',benchmark],['Analysis start',start],['Holdings',String((d.holdings||[]).length)],['Expected return',pct(weightedExpected(d.holdings||[]))]].map(([a,b])=>`<span><small>${esc(a)}</small><strong>${esc(b)}</strong></span>`).join('');$('#freshness').textContent=`Portfolio snapshot: ${d.generated_utc||'available'}${bref?.as_of?` · Benchmark sector reference: ${bref.as_of}`:''}`;$('#trackRecordNotice').textContent=md.performance_basis||'The historical series applies current portfolio weights across available adjusted price history and is not transaction-weighted realized client performance.';}
function renderOverview(d,bref){const m=d.metrics||{},h=d.holdings||[],ts=d.timeseries||[],period=periodRows(ts),ytd=period.find(x=>x.label==='YTD');const expected=weightedExpected(h);$('#overviewMetrics').innerHTML=[['YTD model',pct(ytd?.portfolio)],['YTD benchmark',pct(ytd?.benchmark)],['YTD excess',pct(ytd?.active)],['Ann. volatility',pct(m.annualized_volatility)],['Sharpe',num(m.sharpe)],['Max drawdown',pct(m.max_drawdown)],['Expected return',pct(expected)],['Tracking error',pct(m.tracking_error)]].map(x=>metric(...x)).join('');plot('overviewGrowthChart',[{type:'scatter',mode:'lines',name:'Model portfolio',x:ts.map(x=>x.date),y:ts.map(x=>x.portfolio_growth)},{type:'scatter',mode:'lines',name:'Benchmark',x:ts.map(x=>x.date),y:ts.map(x=>x.benchmark_growth)}],{yaxis:{title:'Growth of 1.0'}});$('#constructionMetrics').innerHTML=[['Holdings',h.length],['Top 5 weight',pct(m.top_5_weight??h.sort((a,b)=>b.weight-a.weight).slice(0,5).reduce((s,x)=>s+(+x.weight||0),0))],['Effective holdings',num(m.effective_number_of_holdings,1)],['Largest weight',pct(m.top_1_weight??Math.max(...h.map(x=>+x.weight||0)))],['Largest risk share',pct(m.largest_risk_contribution)],['Effective sectors',num(m.effective_number_of_sectors,1)]].map(x=>metric(...x)).join('');plot('overviewWeightsChart',[{type:'bar',orientation:'h',y:[...h].sort((a,b)=>a.weight-b.weight).map(x=>x.company),x:[...h].sort((a,b)=>a.weight-b.weight).map(x=>x.weight)}],{xaxis:{tickformat:'.0%'},margin:{l:190,r:20,t:10,b:45}});renderSectorChart('overviewSectorChart',h,bref,false);const c=d.portfolio_characteristics||{};const score=weightedResearchScore(d.theses||[]);$('#characteristicMetrics').innerHTML=[['Forward P/E',mult(c.weighted_forward_pe)],['Revenue growth',pct(c.weighted_revenue_growth)],['Operating margin',pct(c.weighted_operating_margin)],['ROE',pct(c.weighted_roe)],['Research score',score==null?'—':`${num(score,2)} / 5`],['Expected return',pct(expected)]].map(x=>metric(...x)).join('');}

function renderPerformance(d){const ts=d.timeseries||[],rows=periodRows(ts);$('#performanceAsOf').textContent=ts.length?`Through ${ts[ts.length-1].date}`:'No history';$('#performanceTable').innerHTML=`<thead><tr><th>Period</th><th>Model portfolio</th><th>Benchmark</th><th>Excess return</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.label)}${r.annualized?' <span class="annualized">annualized</span>':''}</td><td>${pct(r.portfolio)}</td><td>${pct(r.benchmark)}</td><td class="${(r.active??0)>=0?'positive':'negative'}">${pct(r.active)}</td></tr>`).join('')}</tbody>`;plot('performanceGrowthChart',[{type:'scatter',mode:'lines',name:'Model portfolio',x:ts.map(x=>x.date),y:ts.map(x=>x.portfolio_growth)},{type:'scatter',mode:'lines',name:'Benchmark',x:ts.map(x=>x.date),y:ts.map(x=>x.benchmark_growth)}],{yaxis:{title:'Growth of 1.0'}});plot('drawdownChart',[{type:'scatter',mode:'lines',name:'Model portfolio',x:ts.map(x=>x.date),y:drawdowns(ts,'portfolio_growth'),fill:'tozeroy'},{type:'scatter',mode:'lines',name:'Benchmark',x:ts.map(x=>x.date),y:drawdowns(ts,'benchmark_growth')}],{yaxis:{tickformat:'.0%',title:'Drawdown'}});const cal=calendarReturns(ts);$('#calendarReturnTable').innerHTML=`<thead><tr><th>Year</th><th>Model</th><th>Benchmark</th><th>Excess</th></tr></thead><tbody>${cal.map(r=>`<tr><td>${r.year}</td><td>${pct(r.portfolio)}</td><td>${pct(r.benchmark)}</td><td>${pct(r.portfolio-r.benchmark)}</td></tr>`).join('')}</tbody>`;renderMonthlyHeatmap(ts);renderRollingRisk(d.rolling_risk||[]);const md=d.metadata||{};$('#performanceMethodology').textContent=md.performance_basis||'Current portfolio weights are applied across available adjusted price history. This is a research model rather than a transaction-weighted realized track record.';$('#currencyMethodology').textContent=md.currency_basis||'The current research series uses listing-currency adjusted price returns; FX is not normalized to a single reporting currency.';}
function renderMonthlyHeatmap(ts){const vals=monthlyReturns(ts),years=[...new Set(Object.keys(vals).map(k=>+k.slice(0,4)))].sort((a,b)=>b-a).slice(0,6).sort((a,b)=>a-b),months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];if(!years.length){noData('monthlyHeatmap');return;}const z=years.map(y=>months.map((_,i)=>vals[`${y}-${String(i+1).padStart(2,'0')}`]??null));plot('monthlyHeatmap',[{type:'heatmap',x:months,y:years.map(String),z,text:z.map(r=>r.map(v=>v==null?'':pct(v))),texttemplate:'%{text}',hovertemplate:'%{y} %{x}: %{z:.1%}<extra></extra>',zmid:0}],{margin:{l:55,r:20,t:10,b:40}});}
function renderRollingRisk(rows){if(!rows.length){$('#rollingRiskTable').innerHTML='<tbody><tr><td class="muted">Rolling-risk detail will populate after the next research refresh.</td></tr></tbody>';return;}$('#rollingRiskTable').innerHTML=`<thead><tr><th>Window</th><th>Latest return</th><th>Volatility</th><th>Tracking error</th><th>Worst rolling</th><th>Best rolling</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.window)}</td><td>${pct(r.latest_return)}</td><td>${pct(r.latest_volatility)}</td><td>${pct(r.latest_tracking_error)}</td><td>${pct(r.worst_rolling_return)}</td><td>${pct(r.best_rolling_return)}</td></tr>`).join('')}</tbody>`;}

function sectorData(h,bref){const p={};h.forEach(x=>{const s=canonicalSector(x.sector);p[s]=(p[s]||0)+(+x.weight||0)});const b=bref?.sector_weights||{};const sectors=[...new Set([...Object.keys(p),...Object.keys(b)])].filter(x=>x!=='Unknown');return sectors.map(s=>({sector:s,portfolio:p[s]||0,benchmark:+b[s]||0,active:(p[s]||0)-(+b[s]||0)})).sort((a,b)=>b.portfolio-a.portfolio);}
function renderSectorChart(id,h,bref,activeOnly=false){const rows=sectorData(h,bref);if(!rows.length){noData(id);return;}plot(id,activeOnly?[{type:'bar',x:rows.map(x=>x.sector),y:rows.map(x=>x.active),name:'Active weight'}]:[{type:'bar',x:rows.map(x=>x.sector),y:rows.map(x=>x.portfolio),name:'Portfolio'},{type:'bar',x:rows.map(x=>x.sector),y:rows.map(x=>x.benchmark),name:'S&P 500'}],{barmode:'group',yaxis:{tickformat:'.0%'},xaxis:{tickangle:-25},margin:{l:55,r:15,t:10,b:105}});}
function renderPortfolio(d,bref){const h=d.holdings||[];const rows=sectorData(h,bref);renderSectorChart('sectorActiveChart',h,bref,false);$('#sectorTable').innerHTML=`<thead><tr><th>Sector</th><th>Portfolio</th><th>S&P 500</th><th>Active</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.sector)}</td><td>${pct(r.portfolio)}</td><td>${pct(r.benchmark)}</td><td class="${r.active>=0?'positive':'negative'}">${pct(r.active)}</td></tr>`).join('')}</tbody>`;$('#benchmarkSectorNote').innerHTML=bref?`Benchmark sector reference: ${esc(bref.benchmark)} as of ${esc(bref.as_of)} · ${esc(bref.source)}. Dated reference; not used for return calculations.`:'Benchmark sector reference unavailable.';const geo={};h.forEach(x=>{const c=x.country||'Not classified';geo[c]=(geo[c]||0)+(+x.weight||0)});plot('geographyChart',[{type:'pie',labels:Object.keys(geo),values:Object.values(geo),hole:.45,textinfo:'label+percent'}],{showlegend:false});$('#holdingsTable').innerHTML=`<thead><tr><th>Company</th><th>Sector</th><th>Country</th><th>Weight</th><th>Expected return</th><th>Risk contribution</th></tr></thead><tbody>${h.map(x=>`<tr><td><button class="table-link company-jump" data-company="${esc(x.company)}">${esc(x.company||'—')}</button></td><td>${esc(x.sector||'—')}</td><td>${esc(x.country||'—')}</td><td>${pct(x.weight)}</td><td>${pct(x.expected_annual_return)}</td><td>${pct(x.risk_contribution)}</td></tr>`).join('')}</tbody>`;$$('.company-jump').forEach(b=>b.addEventListener('click',()=>openCompanyThesis(b.dataset.company)));plot('riskBudgetChart',[{type:'bar',name:'Capital weight',x:h.map(x=>x.company),y:h.map(x=>x.weight)},{type:'bar',name:'Risk contribution',x:h.map(x=>x.company),y:h.map(x=>x.risk_contribution)}],{barmode:'group',yaxis:{tickformat:'.0%'},xaxis:{tickangle:-30},margin:{l:55,r:15,t:10,b:125}});renderUnderwriting(d.theses||[]);}
function weightedResearchScore(items){const a=items.filter(x=>x.composite_score!=null&&x.weight!=null);const w=a.reduce((s,x)=>s+(+x.weight||0),0);return w?a.reduce((s,x)=>s+(+x.weight||0)*(+x.composite_score||0),0)/w:null;}
function renderUnderwriting(items){const keys=['business_quality','moat_score','management_capital_allocation','balance_sheet','growth','valuation','risk_resilience'],labels=keys.map(scoreLabel),vals=keys.map(k=>{const a=items.filter(x=>x.scores?.[k]!=null&&x.weight!=null);const w=a.reduce((s,x)=>s+(+x.weight||0),0);return w?a.reduce((s,x)=>s+(+x.weight||0)*(+x.scores[k]||0),0)/w:null});if(!vals.some(x=>x!=null)){noData('underwritingChart','No published scorecards available.');return;}plot('underwritingChart',[{type:'bar',x:labels,y:vals,text:vals.map(v=>num(v,1)),textposition:'outside'}],{yaxis:{range:[0,5.4],dtick:1},xaxis:{tickangle:-20},margin:{l:45,r:20,t:10,b:110}});}

function scoreLabel(k){return ({business_quality:'Business quality',moat_score:'Moat',management_capital_allocation:'Management / capital allocation',balance_sheet:'Balance sheet',growth:'Growth',valuation:'Valuation',risk_resilience:'Risk / resilience'})[k]||k.replaceAll('_',' ');}
function renderThesisOverview(items){const sorted=[...items].filter(x=>x.expected_annual_return!=null).sort((a,b)=>b.expected_annual_return-a.expected_annual_return);if(!sorted.length){noData('returnOverviewChart','Expected-return assumptions are not available yet.');return;}plot('returnOverviewChart',[{type:'bar',orientation:'h',y:sorted.map(x=>x.company),x:sorted.map(x=>x.expected_annual_return),text:sorted.map(x=>pct(x.expected_annual_return)),textposition:'outside',hovertemplate:'%{y}<br>Expected return: %{x:.1%}<extra></extra>'}],{xaxis:{tickformat:'.0%',title:'Base-case annualized expected return'},yaxis:{automargin:true,autorange:'reversed'},margin:{l:220,r:70,t:10,b:55}});}
function renderCompanyThesis(item){if(!item)return;$('#companyHeader').innerHTML=`<div class="company-title-row"><div><p class="eyebrow">${esc(item.sector||'PORTFOLIO HOLDING')}</p><h2>${esc(item.company)}</h2><p class="muted">${esc(item.status||'Active')} · ${esc(item.time_horizon||'Long term')}${item.country?` · ${esc(item.country)}`:''}</p></div><div class="return-pill"><span>Base-case expected return</span><strong>${pct(item.expected_annual_return)}</strong><small>annualized scenario estimate</small></div></div><div class="metric-grid compact company-metrics">${metric('Portfolio weight',pct(item.weight))}${metric('Expected return',pct(item.expected_annual_return),'Base case')}${metric('Conviction',item.conviction==null?'—':`${num(item.conviction,1)} / 5`)}${metric('Research score',item.composite_score==null?'—':`${num(item.composite_score,2)} / 5`)}${metric('Time horizon',item.time_horizon||'—')}</div>`;const scores=item.scores||{},keys=Object.keys(scores);if(keys.length){plot('companyScoreChart',[{type:'bar',x:keys.map(scoreLabel),y:keys.map(k=>scores[k]),text:keys.map(k=>num(scores[k],1)),textposition:'outside'}],{yaxis:{range:[0,5.4],dtick:1},xaxis:{tickangle:-20},margin:{l:45,r:20,t:10,b:110}});}else noData('companyScoreChart','No scorecard published.');$('#decisionFrame').innerHTML=`<div class="decision-item"><span>Why it is owned</span><p>${esc(item.why_owned||'—')}</p></div><div class="decision-item"><span>What changes the mind</span><p>${esc(item.sell_condition||'—')}</p></div><div class="decision-item"><span>What is monitored</span><p>${esc(item.monitoring_kpi||'—')}</p></div>`;$('#companyThesisBody').innerHTML=[fieldCard('Investment Thesis',item.investment_thesis,'thesis-primary'),fieldCard('Competitive Advantage / Moat',item.competitive_advantage),fieldCard('Growth Drivers',item.growth_drivers),fieldCard('Valuation Rationale',item.valuation_rationale,'valuation-card'),fieldCard('Catalysts',item.catalysts),fieldCard('Key Risks',item.key_risks,'risk-card'),fieldCard('Falsification / Sell Condition',item.sell_condition,'risk-card'),fieldCard('Monitoring KPIs',item.monitoring_kpi),fieldCard('Research Notes',item.public_notes)].join('');}
function renderTheses(items){thesisItems=items.filter(x=>x.company);const sel=$('#thesisCompanySelect');sel.innerHTML=thesisItems.map((x,i)=>`<option value="${i}">${esc(x.company)}</option>`).join('');renderThesisOverview(thesisItems);if(thesisItems.length)renderCompanyThesis(thesisItems[0]);sel.addEventListener('change',()=>renderCompanyThesis(thesisItems[+sel.value]));}
function openCompanyThesis(company){if(!thesisItems.length)return;const idx=thesisItems.findIndex(x=>x.company===company||x.company.toLowerCase().includes(String(company).toLowerCase()));const safe=idx>=0?idx:0;$('#thesisCompanySelect').value=String(safe);renderCompanyThesis(thesisItems[safe]);activateTab('theses');}

function renderRisk(d){const m=d.metrics||{};$('#riskMetrics').innerHTML=[['Tracking error',pct(m.tracking_error)],['Information ratio',num(m.information_ratio)],['Beta',num(m.beta)],['Benchmark corr.',num(m.benchmark_correlation)],['Upside capture',pct(m.up_capture)],['Downside capture',pct(m.down_capture)],['Daily ES 95%',pct(m.daily_expected_shortfall_95,2)],['CAPM alpha',pct(m.annualized_alpha)]].map(x=>metric(...x)).join('');const a=d.attribution||[];if(a.length){const ordered=[...a].sort((x,y)=>y.contribution-x.contribution);plot('attributionChart',[{type:'bar',orientation:'h',y:ordered.map(x=>x.company),x:ordered.map(x=>x.contribution)}],{xaxis:{tickformat:'.1%',title:'Static arithmetic contribution'},margin:{l:210,r:20,t:10,b:50}});$('#attributionTable').innerHTML=`<thead><tr><th>Company</th><th>Weight</th><th>Asset return</th><th>Contribution</th></tr></thead><tbody>${ordered.map(x=>`<tr><td>${esc(x.company)}</td><td>${pct(x.weight)}</td><td>${pct(x.asset_total_return)}</td><td class="${x.contribution>=0?'positive':'negative'}">${pct(x.contribution,2)}</td></tr>`).join('')}</tbody>`;}else{noData('attributionChart');$('#attributionTable').innerHTML='<tbody><tr><td class="muted">Attribution will populate after the next successful research refresh.</td></tr></tbody>';}if(d.factors?.length)plot('factorChart',[{type:'bar',x:d.factors.map(x=>x.factor),y:d.factors.map(x=>x.exposure)}]);else noData('factorChart');if(d.stress?.length)plot('stressChart',[{type:'bar',x:d.stress.map(x=>x.scenario),y:d.stress.map(x=>x.estimated_return)}],{yaxis:{tickformat:'.0%'}});else noData('stressChart');renderHistoricalStress(d.historical_stress||[]);renderAlpha(d.alpha||[]);}
function renderHistoricalStress(rows){if(!rows.length){$('#historicalStressTable').innerHTML='<tbody><tr><td class="muted">Historical stress-window detail will populate after the next research refresh.</td></tr></tbody>';return;}$('#historicalStressTable').innerHTML=`<thead><tr><th>Scenario</th><th>Model</th><th>Benchmark</th><th>Active</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.scenario)}</td><td>${pct(r.portfolio_return)}</td><td>${pct(r.benchmark_return)}</td><td>${pct(r.active_return)}</td></tr>`).join('')}</tbody>`;}
function renderAlpha(rows){if(!rows.length){$('#alphaTable').innerHTML='<tbody><tr><td class="muted">Alpha regressions unavailable.</td></tr></tbody>';return;}$('#alphaTable').innerHTML=`<thead><tr><th>Model</th><th>Annualized alpha</th><th>t-stat</th><th>p-value</th><th>R²</th><th>5% significance</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.model)}</td><td>${pct(r.annualized_alpha)}</td><td>${num(r.t_stat)}</td><td>${r.p_value==null?'—':(+r.p_value).toFixed(4)}</td><td>${pct(r.r2)}</td><td>${r.significant_5pct?'Yes':'No'}</td></tr>`).join('')}</tbody>`;}

function researchMerge(d){const h=new Map((d.holdings||[]).map(x=>[x.company,x])),r=new Map((d.reverse_dcf||[]).map(x=>[x.company,x]));return(d.theses||[]).map(t=>({...h.get(t.company),...t,reverse_dcf:r.get(t.company)||null}));}
function renderResearch(d){researchItems=researchMerge(d);const sel=$('#researchCompanySelect');sel.innerHTML=researchItems.map((x,i)=>`<option value="${i}">${esc(x.company)}</option>`).join('');$('#researchLibrary').innerHTML=researchItems.map((x,i)=>`<button class="research-card" data-research="${i}"><span class="eyebrow">${esc(x.sector||'EQUITY')}</span><strong>${esc(x.company)}</strong><div><span>Expected return ${pct(x.expected_annual_return)}</span><span>Score ${x.composite_score==null?'—':`${num(x.composite_score,1)}/5`}</span></div></button>`).join('');$$('[data-research]').forEach(b=>b.addEventListener('click',()=>{sel.value=b.dataset.research;renderResearchDetail(researchItems[+b.dataset.research]);document.querySelector('#researchDetail').scrollIntoView({behavior:'smooth',block:'start'});}));if(researchItems.length)renderResearchDetail(researchItems[0]);sel.addEventListener('change',()=>renderResearchDetail(researchItems[+sel.value]));}
function renderResearchDetail(x){if(!x)return;const rd=x.reverse_dcf||{};$('#researchDetail').innerHTML=`<div class="research-detail-head"><div><p class="eyebrow">${esc(x.sector||'EQUITY RESEARCH')}</p><h2>${esc(x.company)}</h2><p class="muted">${esc(x.industry||'')} ${x.country?`· ${esc(x.country)}`:''}</p></div><button class="button-link" id="researchToThesis">Open full thesis →</button></div><div class="metric-grid compact research-metrics">${metric('Expected return',pct(x.expected_annual_return),'Base case')}${metric('Forward P/E',mult(x.forward_pe))}${metric('Revenue growth',pct(x.revenue_growth))}${metric('Operating margin',pct(x.operating_margin))}${metric('ROE',pct(x.roe))}${metric('Reverse-DCF FCF growth',pct(rd.implied_annual_fcf_growth))}${metric('Research score',x.composite_score==null?'—':`${num(x.composite_score,2)} / 5`)}${metric('Conviction',x.conviction==null?'—':`${num(x.conviction,1)} / 5`)}</div><div class="grid two"><div class="research-copy"><h3>Investment case</h3><p>${esc(x.investment_thesis||'Thesis text will populate after the next thesis refresh.')}</p></div><div class="research-copy"><h3>Valuation & market expectations</h3><p>${esc(x.valuation_rationale||'Valuation rationale will populate after the next thesis refresh.')}</p>${rd.wacc!=null?`<p class="footnote">Reverse DCF: ${pct(rd.implied_annual_fcf_growth)} implied annual FCF growth over ${num(rd.forecast_years,0)} years using ${pct(rd.wacc)} WACC and ${pct(rd.terminal_growth)} terminal growth.</p>`:'<p class="footnote">Reverse-DCF diagnostics will populate after the next successful research refresh.</p>'}</div></div><div class="research-copy risk-copy"><h3>Key risks</h3><p>${esc(x.key_risks||'—')}</p></div>`;$('#researchToThesis').addEventListener('click',()=>openCompanyThesis(x.company));}

function renderPhilosophy(p){if(!p||!Object.keys(p).length){$('#philosophyCard').innerHTML='<h2>Portfolio philosophy</h2><p class="muted">No public philosophy text has been published yet.</p>';return;}const fields=[['Investment Philosophy','investment_philosophy'],['Portfolio Objective','portfolio_objective'],['Research Process','research_process'],['Selection Criteria','selection_criteria'],['Position Sizing','position_sizing'],['Diversification','diversification'],['Risk Management','risk_management'],['Sell Discipline','sell_discipline'],['Monitoring & Review','monitoring_and_review'],['Portfolio Edge','portfolio_edge'],['What I Avoid','what_i_avoid'],['Closing Summary','closing_summary']];$('#philosophyCard').innerHTML=`<h2>Portfolio Philosophy</h2><div class="metric-grid compact">${metric('Benchmark',p.benchmark||'—')}${metric('Time horizon',p.time_horizon||'—')}${metric('Return objective',p.return_objective||'—')}</div><div class="thesis-grid">${fields.filter(x=>p[x[1]]).map(([t,k])=>`<div class="thesis-block"><h3>${esc(t)}</h3><p>${esc(p[k])}</p></div>`).join('')}</div>`;}

async function init(){try{const [snapRes,overRes,benchRes]=await Promise.all([fetch(`data/portfolio_snapshot.json?v=${Date.now()}`,{cache:'no-store'}),fetch(`data/thesis_overrides.json?v=${Date.now()}`,{cache:'no-store'}),fetch(`data/benchmark_reference.json?v=${Date.now()}`,{cache:'no-store'})]);if(!snapRes.ok)throw new Error('snapshot unavailable');const snapshot=await snapRes.json(),overrides=overRes.ok?await overRes.json():{companies:[]};benchmarkRef=benchRes.ok?await benchRes.json():null;appData=applyOverrides(snapshot,overrides);renderHero(appData,benchmarkRef);renderOverview(appData,benchmarkRef);renderPerformance(appData);renderPortfolio(appData,benchmarkRef);renderTheses(appData.theses||[]);renderRisk(appData);renderResearch(appData);renderPhilosophy(appData.portfolio_philosophy||{});const hash=location.hash.replace('#','');if(['overview','performance','portfolio','theses','risk','research','philosophy'].includes(hash))activateTab(hash);}catch(e){console.error(e);$('#freshness').textContent='Latest portfolio snapshot is temporarily unavailable.';$('#overview').insertAdjacentHTML('afterbegin','<article class="card"><h2>Data temporarily unavailable</h2><p>Please reload after the next successful portfolio refresh.</p></article>');}}
init();
